version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.236-jdk11
    restart: always
    ports:
     - 8080:8080
     - 50000:50000
    volumes:
     - /var/lib/jenkins:/var/jenkins_home
  sonar:
    container_name: sonarqube
    image: sonarqube:8.3.1-community
    ports:
     - 9000:9000
    volumes:
     - /opt/sonarqube/data:/opt/sonarqube/data
     - /opt/sonarqube/extensions:/opt/sonarqube/extensions
     - /opt/sonarqube/logs:/opt/sonarqube/logs
    environment:
      sonar.jdbc.url: jdbc:postgresql://postgres:5432/sonar_qube
      sonar.jdbc.username: sonar
      sonar.jdbc.password: sonar
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  db:
    container_name: postgres
    image: postgres:12.2
    restart: always
    ports:
     - "5432:5432"
    volumes:
     - /opt/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sonar_qube
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
